cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: https://prometheus-prod-24-prod-eu-west-2.grafana.net
    basicAuth:
      username: "1601239"
      password: glc_eyJvIjoiMTEzNDUxNiIsIm4iOiJzdGFjay05NDI3NzUtaW50ZWdyYXRpb24tbW92aW1pbmdsZS0yLW1vdmltaW5nbGUtMiIsImsiOiJaOTcxM0JpM3I4V0E1ME96Nk1LaVlSTjIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
  loki:
    host: https://logs-prod-012.grafana.net
    basicAuth:
      username: "900556"
      password: glc_eyJvIjoiMTEzNDUxNiIsIm4iOiJzdGFjay05NDI3NzUtaW50ZWdyYXRpb24tbW92aW1pbmdsZS0yLW1vdmltaW5nbGUtMiIsImsiOiJaOTcxM0JpM3I4V0E1ME96Nk1LaVlSTjIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
  tempo:
    host: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
    basicAuth:
      username: "894872"
      password: glc_eyJvIjoiMTEzNDUxNiIsIm4iOiJzdGFjay05NDI3NzUtaW50ZWdyYXRpb24tbW92aW1pbmdsZS0yLW1vdmltaW5nbGUtMiIsImsiOiJaOTcxM0JpM3I4V0E1ME96Nk1LaVlSTjIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: my-cluster
    prometheus:
      external:
        url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}