name: Integration Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Check services are running
        run: docker-compose ps

      - name: Send test message
        run: |
          curl -f http://localhost:8080/send?message=Hello
          echo "Message sent to the voting service."

      - name: Wait for log file update
        run: sleep 10

      - name: Check logs for the message
        id: check_logs
        run: |
          if [ -f ./logs/application.log ]; then
            if grep -q 'Hello' ./logs/application.log; then
              echo "message_status=found" >> $GITHUB_ENV
            else
              echo "message_status=not found" >> $GITHUB_ENV
              exit 1
            fi
          else
            echo "./logs/application.log does not exist."
            exit 1
          fi

      - name: Output result
        if: env.message_status == 'found'
        run: echo "Test message received by the voting service."

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./logs/application.log

      - name: Clean up
        run: docker-compose down
