name: Integration Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Check services are running
        run: docker-compose ps

      - name: Send test message
        run: |
          curl -f http://localhost:8080/send?message=Hello
          echo "Message sent to the voting service."

      - name: Wait for log file update
        run: sleep 10

      - name: Collect all files for diagnostics
        run: |
          mkdir -p artifacts
          cp -r ./logs/ artifacts/logs/  # Adjust as necessary for other directories
          cp -r /path/to/other/important/files/ artifacts/other_files/

      - name: Upload all artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all-artifacts
          path: artifacts/

      - name: Clean up
        run: docker-compose down
