name: Integration Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set executable permissions for scripts
        run: chmod +x ./init-cassandra.sh ./scripts/run-integration-tests.sh

      - name: Run integration tests
        run: ./scripts/run-integration-tests.sh

      - name: Upload all artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all-artifacts
          path: artifacts/

      - name: Clean up
        if: always()
        run: docker-compose down
