name: Integration Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:4
        ports:
          - 9042:9042
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Check services are running
        run: docker-compose ps

      - name: Send test message
        run: |
          curl -f http://localhost:8080/send?message=Hello
          echo "Message sent to the voting service."

      - name: Wait for log file update
        run: sleep 10  # Adjust the timing as necessary

      - name: Check logs for the message
        id: check_logs
        run: |
          if grep -q 'Hello' ./logs/voting-service.log; then
            echo "::set-output name=message_status::found"
          else
            echo "::set-output name=message_status::not found"
            exit 1
          fi

      - name: Output result
        if: steps.check_logs.outputs.message_status == 'found'
        run: echo "Test message received by the voting service."

      - name: Clean up
        run: docker-compose down
